CP-51325: Updating Zip Sharp Library
xenserver/dotnet-packages pull request #107
Opened 2024-09-11 10:11 UTC by ElijahSadorra

- Updated READ.me to correct new version of SharpZipLib, clarified steps and corrected wrong command
- Updated new version of SharpZipLib from 0.85.4 to 1.3.3 with 0 vulnerabilities
- Removed all SharpZipLib patches
- Updates `.csproj` patch file to target net4.8

2024-09-16 13:00 UTC, danilo-delbusso requested changes

2024-09-16 13:00 UTC, danilo-delbusso commented on build.ps1
> +dotnet restore -v n "$SCRATCH_DIR\sharpziplib\SharpZipLib-1.3.3\src\ICSharpCode.SharpZipLib\ICSharpCode.SharpZipLib.csproj"
since you're passing `$RESTORE_SWITCHES -p:RestoreConfigFile=$RESTORE_NUGET_CONFIG_FILE`, you don't need `dotnet restore`

2024-09-16 13:01 UTC, danilo-delbusso commented
Sign off also missing from c878dc5beb05a5a767c7e371eec274829dbb10d2. Sorry, didn't see that earlier!

2024-09-18 16:37 UTC, danilo-delbusso requested changes

2024-09-18 16:37 UTC, danilo-delbusso commented on build.ps1
> +$RESTORE_SWITCHES= '/restore', '/p:RestoreNoCache=true', "-p:RestoreConfigFile=$RESTORE_NUGET_CONFIG_FILE"
For this to work you'll need to move line 114 above line 81

2024-09-18 16:37 UTC, danilo-delbusso commented on build.ps1
> +Copy-Item "$REPO\$RESTORE_NUGET_CONFIG_FILE" -Destination "$SCRATCH_DIR\$RESTORE_NUGET_CONFIG_FILE"
here you've updated the contents of `Nuget.Config` in the scratch, but `RESTORE_NUGET_CONFIG_FILE` is still pointing to the old one

I think to keep things clean you should move the prepping of Nuget.Config before the initial assignment of RESTORE_SWTICHES, and make sure that the path we pass to `-p:RestoreConfigFile` is the one in the scratch directory.

2024-09-18 16:38 UTC, danilo-delbusso commented on build.ps1
> +Copy-Item "$REPO\$RESTORE_NUGET_CONFIG_FILE" -Destination "$SCRATCH_DIR\$RESTORE_NUGET_CONFIG_FILE"
happy to have a chat if you need clarifications - DM anytime :D

2024-10-03 09:32 UTC, kc284 reviewed
I think we need to direct this PR first to a feature branch for testing and then to master, because there is risk associated with 3 out of the removed patches: the code in the new library has not been fixed (or has not been fixed in exactly the same way) and we don't have enough evidence yet that they're not needed.

2024-10-03 09:32 UTC, kc284 commented on patches/patch-sharpziplib-ca-61725.diff
> -+					TarHeader.GetNameBytes(entry.TarHeader.Name, nameCharIndex, this.blockBuffer, 0, TarBuffer.BlockSize);
As discussed separately, there is a risk here:
- our patch uses longHeader.Size = byteCount;, while their code adds 1
- our patch uses TarHeader.GetNameBytes, while their code uses TarHeader.GetAsciiBytes passing in the additional parameter

2024-10-03 09:32 UTC, kc284 commented on patches/patch-sharpziplib-ca-63358-TarInputStream.diff
> -# Copyright (c) Cloud Software Group, Inc.
Are we sure this patch is not needed anymore?

2024-10-03 09:32 UTC, kc284 commented on patches/patch-sharpziplib-ca-63358-TarBuffer.diff
> -# Copyright (c) Cloud Software Group, Inc.
Are we sure this patch is not needed anymore?

2024-10-08 09:31 UTC, kc284 approved these changes
Approving so we can get a feature branch build to test.

2024-10-08 09:40 UTC, danilo-delbusso approved these changes

2024-10-08 09:40 UTC, merged