CA-368320: Update Json.NET from 10.0.2 to 13.0.1 (#94)
xenserver/dotnet-packages pull request #96
Opened 2022-08-12 09:32 UTC by danilo-delbusso

This backports https://github.com/xenserver/dotnet-packages/pull/94 since I mistakenly merged before branching! PR with package changes coming after.

The commit is simply the cherry picked squash of the PR above.

2022-08-12 09:34 UTC, kc284 approved these changes

2022-08-16 08:35 UTC, CitrixChris requested changes

2022-08-16 08:35 UTC, CitrixChris commented on build.ps1
> +& $msbuild $SWITCHES $RESTORE_SWITCHES -p:RestoreConfigFile=$RESTORE_NUGET_CONFIG_FILE $VS2019 $SIGN "$SCRATCH_DIR\json.net\Newtonsoft.Json\Newtonsoft.Json.csproj"
arent we switching to VS2022?

2022-08-16 08:39 UTC, danilo-delbusso commented on build.ps1
> +& $msbuild $SWITCHES $RESTORE_SWITCHES -p:RestoreConfigFile=$RESTORE_NUGET_CONFIG_FILE $VS2019 $SIGN "$SCRATCH_DIR\json.net\Newtonsoft.Json\Newtonsoft.Json.csproj"
answered in private

2022-08-16 08:40 UTC, CitrixChris approved these changes

2022-08-16 08:41 UTC, merged