[master] Add .NET Standard 2.0 as target for Json.NET
xenserver/dotnet-packages pull request #99
Opened 2022-10-25 12:29 UTC by danilo-delbusso

2022-10-27 13:32 UTC, CitrixChris requested changes

2022-10-27 13:32 UTC, CitrixChris commented on README.md
> +4. Net Standard 2.0 installed.
Numbering is off 1,2 -> 4
Where is 3?

2022-10-27 13:39 UTC, CitrixChris approved these changes

2022-10-28 11:28 UTC, kc284 approved these changes

2022-10-28 11:30 UTC, merged